AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'

Style/Encoding:
  Enabled: false
Style/BlockComments:
  Enabled: false

Metrics/LineLength:
  Max: 119
Metrics/MethodLength:
  Max: 15
Documentation:
  Enabled: true
